"""empty message

Revision ID: 1899be59549e
Revises: 
Create Date: 2024-01-29 21:59:26.561886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1899be59549e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_value', sa.Integer(), nullable=True),
    sa.Column('delivery_distance', sa.Integer(), nullable=True),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('delivery_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_distance')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_fee')
    # ### end Alembic commands ###
