"""empty message

Revision ID: e5da1c796fad
Revises: 
Create Date: 2024-01-31 19:32:28.159280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5da1c796fad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_fee')
    # ### end Alembic commands ###
